main: pw.alphabeta.authyou.client.AuthYouPlugin
name: AuthYou
version: 2.0.0
description: Authenticate user
api-version: 1.12.2
authors: [ksi123456ab]
commands:
  authyou:
    description: manage authyou
    usage: /authoyu list, /authyou addname <username>, /authyou removename <username>, /authyou adduuid <uuid>, /authyou removeuuid <uuid>