main: pw.alphabeta.authyoubungee.client.AuthYouPlugin
name: AuthYou
version: 2.0.0
description: Authenticate user
authors: [ksi123456ab]
commands:
  list:
    description: list allowUser
    usage: /authoyu list
  addname:
    description: add username to allowUser list
    usage: /authyou addname <username>
  removename:
    description: remove username to allowUser list
    usage: /authyou removename <username>
  adduuid:
    description: add uuid to allowUser list
    usage: /authyou adduuid <uuid>
  removeuuid:
    description: remove uuid to allowUser list
    usage: /authyou removeuuid <uuid>